language: php

php:
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"

before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.4" || ${TRAVIS_PHP_VERSION:0:3} == "5.3" ]]; then composer require satooshi/php-coveralls:1.0.1; else composer require satooshi/php-coveralls:dev-master; fi
  - composer install

script:
  - phpunit --coverage-clover tmp/clover.xml

after_success:
  - php vendor/bin/coveralls -v